### PR TITLE
fix #3 override in MigrationCreator for Laravel 5.4

### LINKED ISSUE #3: migration creator no longer works with laravel 5.4
The framework no longer calls getStubPath() in Laravel 5.4 in the overridden migration creator

### PR DESCRIPTION
**Pull request by miklcct**
This fixes #3 by overriding methods in both Laravel 5.3 and 5.4

### CODE REVIEW

**Comment by Kyslik** [comment]
So this fix is suitable for all versions pre 5.4? (since you left old method there)

**Comment by miklcct** [comment]
No behavioural change for pre 5.4 versions since the old method is not touched at all.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Kyslik** [comment]
Merged and tagged (soon), thanks :).

I will check other MakeCommands.

**Comment by Kyslik** [comment]
For L5.4 use package version `2.*`, thanks for informing me.

**Pull request merged**
